'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { MyComponent as MyComponentElement, defineCustomElement as defineMyComponent } from "@fdiskas/stencil-library/dist/components/my-component.js";
import { PocButton as PocButtonElement, defineCustomElement as definePocButton } from "@fdiskas/stencil-library/dist/components/poc-button.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type MyComponentEvents = NonNullable<unknown>;

export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents> = /*@__PURE__*/ createComponent<MyComponentElement, MyComponentEvents>({
    tagName: 'my-component',
    elementClass: MyComponentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MyComponentEvents,
    defineCustomElement: defineMyComponent
});

export type PocButtonEvents = NonNullable<unknown>;

export const PocButton: StencilReactComponent<PocButtonElement, PocButtonEvents> = /*@__PURE__*/ createComponent<PocButtonElement, PocButtonEvents>({
    tagName: 'poc-button',
    elementClass: PocButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as PocButtonEvents,
    defineCustomElement: definePocButton
});
