/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PocButton {
        /**
          * Disables user interaction.
          * @default false
         */
        "disabled": boolean;
        /**
          * Button size.
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * Native button type.
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * Visual style variant.
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary';
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPocButtonElement extends Components.PocButton, HTMLStencilElement {
    }
    var HTMLPocButtonElement: {
        prototype: HTMLPocButtonElement;
        new (): HTMLPocButtonElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "poc-button": HTMLPocButtonElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PocButton {
        /**
          * Disables user interaction.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Button size.
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * Native button type.
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * Visual style variant.
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary';
    }

    interface MyComponentAttributes {
        "first": string;
        "middle": string;
        "last": string;
    }
    interface PocButtonAttributes {
        "variant": 'primary' | 'secondary';
        "size": 'sm' | 'md' | 'lg';
        "disabled": boolean;
        "type": 'button' | 'submit' | 'reset';
    }

    interface IntrinsicElements {
        "my-component": Omit<MyComponent, keyof MyComponentAttributes> & { [K in keyof MyComponent & keyof MyComponentAttributes]?: MyComponent[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `attr:${K}`]?: MyComponentAttributes[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `prop:${K}`]?: MyComponent[K] };
        "poc-button": Omit<PocButton, keyof PocButtonAttributes> & { [K in keyof PocButton & keyof PocButtonAttributes]?: PocButton[K] } & { [K in keyof PocButton & keyof PocButtonAttributes as `attr:${K}`]?: PocButtonAttributes[K] } & { [K in keyof PocButton & keyof PocButtonAttributes as `prop:${K}`]?: PocButton[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.IntrinsicElements["my-component"] & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "poc-button": LocalJSX.IntrinsicElements["poc-button"] & JSXBase.HTMLAttributes<HTMLPocButtonElement>;
        }
    }
}
